### ISSUE TITLE
cannot deploy bdm on a 7.1.3 bonita server

### ISSUE THREAD

**Issue by mehdi-kettani** [Bonitasoft-Community/vacation-management-example#1]
"Updating schema fails due to: [org.h2.jdbc.JdbcSQLException: NULL not allowed for column "NUMBEROFDAYS"; SQL statement: alter table VACATIONREQUEST add column NUMBEROFDAYS integer not null [23502-170] at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) at org.h2.message.DbException.get(DbException.java:169) at org.h2.message.DbException.get(DbException.java:146) at org.h2.table.Column.validateConvertUpdateSequence(Column.java:293) at org.h2.table.Table.validateConvertUpdateSequence(Table.java:689) at org.h2.command.dml.Insert.addRow(Insert.java:159) at org.h2.command.dml.Select.queryFlat(Select.java:524) at org.h2.command.dml.Select.queryWithoutCache(Select.java:618) at org.h2.command.dml.Query.query(Query.java:307) at org.h2.command.dml.Insert.insertRows(Insert.java:132) at org.h2.command.dml.Insert.update(Insert.java:84) at org.h2.command.ddl.CreateTable.update(CreateTable.java:181) at org.h2.command.ddl.AlterTableAlterColumn.execute(AlterTableAlterColumn.java:432) at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:332) at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214) at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150) at org.h2.command.CommandContainer.update(CommandContainer.java:75) at org.h2.command.Command.executeUpdate(Command.java:230) at org.h2.server.TcpServerThread.process(TcpServerThread.java:333) at org.h2.server.TcpServerThread.run(TcpServerThread.java:149) at java.lang.Thread.run(Unknown Source) , org.h2.jdbc.JdbcSQLException: NULL not allowed for column "REQUESTERBONITABPMID"; SQL statement: alter table VACATIONREQUEST add column REQUESTERBONITABPMID bigint not null [23502-170] at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) at org.h2.message.DbException.get(DbException.java:169) at org.h2.message.DbException.get(DbException.java:146) at org.h2.table.Column.validateConvertUpdateSequence(Column.java:293) at org.h2.table.Table.validateConvertUpdateSequence(Table.java:689) at org.h2.command.dml.Insert.addRow(Insert.java:159) at org.h2.command.dml.Select.queryFlat(Select.java:524) at org.h2.command.dml.Select.queryWithoutCache(Select.java:618) at org.h2.command.dml.Query.query(Query.java:307) at org.h2.command.dml.Insert.insertRows(Insert.java:132) at org.h2.command.dml.Insert.update(Insert.java:84) at org.h2.command.ddl.CreateTable.update(CreateTable.java:181) at org.h2.command.ddl.AlterTableAlterColumn.execute(AlterTableAlterColumn.java:432) at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:332) at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:214) at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:150) at org.h2.command.CommandContainer.update(CommandContainer.java:75) at org.h2.command.Command.executeUpdate(Command.java:230) at org.h2.server.TcpServerThread.process(TcpServerThread.java:333) at org.h2.server.TcpServerThread.run(TcpServerThread.java:149) at java.lang.Thread.run(Unknown Source) ]"

**Comment by amottier** [comment]
I cannot reproduce the issue when importing and running the example process [version 1.1.0](https://github.com/Bonitasoft-Community/vacation-management-example/releases/tag/1.1.0).

Are you still able to reproduce the issue?

Can you add more details about steps to reproduce?

Thanks
