### ISSUE TITLE
Example not working in Bonita 7.2

### ISSUE THREAD

**Issue by rdenarie** [Bonitasoft-Community/vacation-management-example#2]
Hello,
I tried to load this example in Bonita 7.2 Studio (Community version),
The validator said that one groovy script is failed to compile 
due to dependency on Logger not satisfied.

I comment lines about this logger in the script, and it was ok for my tests.

**Comment by amottier** [comment]
Example has been updated for Bonita BPM 7.2 and SLF4J is no longer used.

Note that for previous version, [documentation](https://github.com/Bonitasoft-Community/vacation-management-example/tree/1.1.0#installation) mention that you need to add SLF4J logging library and a [note](https://github.com/Bonitasoft-Community/vacation-management-example/tree/1.1.0#slf4j) explain why.
