### ISSUE TITLE
Unable to resolve com.company.model.VacationAvailable

### ISSUE THREAD

**Issue by betoled** [Bonitasoft-Community/vacation-management-example#4]
Hi,

I'm new to Bonita BPM and I'm trying to get the hang of it using your example.
But when trying to run the Example-InitiateVacationAvailable diagram I'm getting a validation error.

In the createOrResetVacationAvailable script there is a message saying that it is unable to resolve com.company.model.VacationAvailable.

How do I fix this ?

Thanks,
Benjamien

**Comment by amottier** [comment]
Hi,

When you imported the Bonita BPM `.bos` file it should have import the process definitions (diagrams) as well as Business Data Model (BDM) definition. BDM includes the definition of `com.company.model.VacationAvailable`.

You can check that BDM was successfully imported by going in `Development -> Business Data Model -> Manage...` Studio menu. Here you should have the `VacationAvailable` listed in the `List of Business Objects` on the left. If you don't I would suggest to try to import again the `.bos` file in the Studio (you would need to confirm the overwrite of existing files).

If you still face this issue can you mention which version of the example and which version of Bonita BPM Studio you are using?

**Comment by betoled** [comment]
Thank you for your response.
For the moment I'm not continuing with Bonita because I lack the time to learn this.
I hope to pick this up in August.
