### ISSUE TITLE
RestAPI extension error getting VacationAvailable attribute

### ISSUE THREAD

**Issue by goenkale** [Bonitasoft-Community/vacation-management-example#6]
Now, queries need p and c parameters to return a list of attributes.
This,
`def vacationAvailable = vacationAvailableDAO.findByBonitaBPMId(employeeId)`
 is throwing
`GRAVE: org.restlet.Component.BonitaSPRestletApplication Exception or error caught in server resource
groovy.lang.MissingMethodException: No signature of method: com.company.model.VacationAvailableDAOImpl.findByBonitaBPMId() is applicable for argument types: (java.lang.Long) values: [2]
Possible solutions: findByBonitaBPMId(java.lang.Long, int, int)`

**FIX**:
Add p and c params to the method:
`vacationAvailableDAO.findByBonitaBPMId(employeeId, 0, 100)`

**Comment by amottier** [comment]
BDM DAO find* methods only need pagination parameters when returning a list.
As bonitaBPMId is an attribute with a unique constraint, findByBonitaBPMId will return a unique object and not a list and therefor doesn't need the pagination parameter.

If you face the issue, solution is to make sure that unique constraint is actually set on the bonitaBPMId attribute (this is done in all versions of this example).
