### ISSUE TITLE
DATE (java.util.LocalDate) need to be formatted

### ISSUE THREAD

**Issue by goenkale** [Bonitasoft-Community/vacation-management-example#7]
Creating the response:

FIX:
def vacationRequestInfo = ["firstName": user.firstName, "lastName": user.lastName, "startDate": currentUserVacationRequest.startDate.**format(DateTimeFormatter.ISO_LOCAL_DATE)**, "returnDate": currentUserVacationRequest.returnDate.**format(DateTimeFormatter.ISO_LOCAL_DATE)**, "numberOfDays": currentUserVacationRequest.numberOfDays, "status": currentUserVacationRequest.status, "taskId": reviewRequestTaskId]

**Comment by amottier** [comment]
Date need to be formatted in a way that it can be parsed by JavaScript Date object.
In version 7.5.0-1.4.1 of the example we use toString() method on the LocalDate objects that returns the date as a String using ISO-8601 format uuuu-MM-dd.

That is exactly the same as calling format(DateTimeFormatter.ISO_LOCAL_DATE) method.
